export * from './errores';
export { EstadoProceso } from './procesos/EstadoProceso';
export { EventoES } from './procesos/EventoES';
export type { InfoProceso } from './procesos/InfoProceso';
export type { IProcesoAdmisible, IProcesoConsulta, IProcesoEjecutable } from './procesos/IProceso';
export { Proceso } from './procesos/Proceso';
export { BloqueMemoria } from './memoria/BloqueMemoria';
export { GestorMemoria } from './memoria/GestorMemoria';
export type { IConsultaMemoria, IGestorMemoria } from './memoria/IGestorMemoria';
export type { InfoBloque } from './memoria/InfoBloque';
export type { IPoliticaAsignacion } from './memoria/politicas/IPoliticaAsignacion';
export { PoliticaAsignacionBase } from './memoria/politicas/PoliticaAsignacionBase';
export { FirstFit } from './memoria/politicas/FirstFit';
export { BestFit } from './memoria/politicas/BestFit';
export { WorstFit } from './memoria/politicas/WorstFit';
export { EventoCpu, type ResultadoEjecucion } from './planificacion/EventoCpu';
export type { IConsultaCpu, IConsultaPlanificador, IPlanificador } from './planificacion/IPlanificador';
export { PlanificadorRoundRobin } from './planificacion/PlanificadorRoundRobin';
export type { ConfiguracionSimulacion } from './simulacion/ConfiguracionSimulacion';
export type { EstadoSistema, ResultadoTick } from './simulacion/EstadoSistema';
export type { IConsultaSimulador, ISimulador } from './simulacion/ISimulador';
export { Metricas } from './simulacion/Metricas';
export { Simulador } from './simulacion/Simulador';
